# Generated by Django 5.0.6 on 2024-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to='files/')),
                ('my_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
